### PR TITLE
Annika's homework - current status

### PR DESCRIPTION
**Pull request by Annika-Klu**
Hey, so for yesterday's homework, I pretty much managed to copy the design. An issue I am having is that my form is wider than its parent though I set its width to 100% with no additional margins and the width+margins of all items _within_ the form sum up to 100% as well. Padding should not affect the whole thing since box-sizing is set to border-box. I cannot figure out where I went wrong. Could be an interesting issue to discuss during class? I set borders to the form element and its parent element so the issue is obvious. See you!

### CODE REVIEW

**Comment by ugurtekbas** [comment]
@Annika-Klu thanks for awesome description. It sounds great! Maybe you can live code the banner for us at the course 😄

**Comment by Annika-Klu** [comment]
...eventually, It occurred to me I had not included Bootstrap!'s JS so of course my "read me" content toggling wasn't working. It now does. I also added an ugly "cookie banner", not really a banner though, just a div with fixed position that is there from the start. Suppose you need JS in order to make it appear after a couple seconds (?)

**Comment by ugurtekbas** [comment]
@Annika-Klu I see that you have very loooooong commit messages. That's not a best practice, try to minimize it. Write `why` you did the changes on your git commits.

**Comment by Annika-Klu** [comment]
> @Annika-Klu I see that you have very loooooong commit messages. That's not a best practice, try to minimize it. Write `why` you did the changes on your git commits.

OK, will do. Thanks!

**Pull request merged**
