### PR TITLE
I added my Homework

### PR DESCRIPTION
**Pull request by shaefelinger**
Added last weeks Subscribe-Homework.

### CODE REVIEW

**Comment by shaefelinger** [comment]
I also added the Error 404-Animation-Homework. (I thought i would have to create a new Pull-Request for that, but it seems that the pushed changes are automatically added. )
I would have loved to have a real Random-Function for the blinking, but i guess i would need Javascript for that.

**Comment by shaefelinger** [comment]
i also added the Shaking Box.

**Comment by shaefelinger** [comment]
I also did the moving-bars animation. First i used a really complicated method with a separate animation for each bar. But then i figured out how to use delay-property and that made it way easier. I am pretty sure that there still could be an easier way to implement this, using a formula instead of a class for each bar...

The page is responsive (without bootstrap), but it had a scrollbar that i didn't like. Once i added bootstrap, i got rid of the scrollbar. (Have to look into that...)

**Comment by shaefelinger** [comment]
Once i had done the moving bars, it was quite easy to also do the moving balls. I don't like the way i centered the balls horizontally using margin-top. There must be a better way...

**Comment by ugurtekbas** [comment]
> I also added the Error 404-Animation-Homework. (I thought i would have to create a new Pull-Request for that, but it seems that the pushed changes are automatically added. )
> I would have loved to have a real Random-Function for the blinking, but i guess i would need Javascript for that.

Yeap, for randomness you'll need JS 😄

**Comment by ugurtekbas** [comment]
I really liked how you arranged your files and tried different approaches.
Perfect practices there 👍

**Pull request merged**
